config/routes.rb
Rails.application.routes.draw do

root 'blog_posts#index'

  get 'about' => 'welcome#about'

  get 'random' => 'welcome#random'

  get 'my_posts' => 'blog_posts#my_posts'

  get 'my_profile' => 'welcome#my_profile'

  get 'users' => 'welcome#users'

  devise_for :users

  resources :comments

  resources :blog_posts
  

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
	belongs_to :user
	has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :blog_post
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         validates :username, uniqueness: true

         has_many :blog_posts
         has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!


  before_action :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
	   devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :username, :name, :location, :birthday) }
	   devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :username, :name, :location, :birthday) }
	end

end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: [:show, :edit, :update, :destroy]

  # GET /blog_posts
  # GET /blog_posts.json
  def index
    @blog_posts = BlogPost.all
  end

  def my_posts
    @blog_posts = BlogPost.where(user_id: current_user.id)
  end

  # GET /blog_posts/1
  # GET /blog_posts/1.json
  def show
    @comment = Comment.new
  end

  # GET /blog_posts/new
  def new
    @blog_post = BlogPost.new
  end

  # GET /blog_posts/1/edit
  def edit
  end




  # POST /blog_posts
  # POST /blog_posts.json
  def create
    @blog_post = BlogPost.new(blog_post_params)

    respond_to do |format|
      if @blog_post.save
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully created.' }
        format.json { render :show, status: :created, location: @blog_post }
      else
        format.html { render :new }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blog_posts/1
  # PATCH/PUT /blog_posts/1.json
  def update
    respond_to do |format|
      if @blog_post.update(blog_post_params)
        format.html { redirect_to @blog_post, notice: 'Blog post was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog_post }
      else
        format.html { render :edit }
        format.json { render json: @blog_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blog_posts/1
  # DELETE /blog_posts/1.json
  def destroy
    @blog_post.destroy
    respond_to do |format|
      format.html { redirect_to blog_posts_url, notice: 'Blog post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog_post
      @blog_post = BlogPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_post_params
      params.require(:blog_post).permit(:title, :author, :blog_entry, :user_id)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to blog_post_path(id: @comment.blog_post_id), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:author, :comment_entry, :blog_post_id, :user_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def about
  end

  def random
  	redirect_to blog_post_path(id: rand(1..BlogPost.all.length))
  end

  def my_profile
  	@user = current_user
  end

  def users
  	@users = User.all
  end
 end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blog_posts/_form.html.erb
<%= form_for(@blog_post) do |f| %>
  <% if @blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
      <% @blog_post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :title, placeholder: "Post Title", class: "form-control" %><br />
  </div>
  <div class="form-group cant-see-me">  
    <%= f.number_field :user_id, value: current_user.id %>
  </div>
  <div class="form-group">   
    <%= f.text_area :blog_entry, placeholder: "Content", rows: "10", class: "form-control" %><br />
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-custom"  %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Editing Blog Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @blog_post %> |
<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/index.html.erb
<p id="notice"><%= notice %></p>



<div class="row">
  <div class="panel panel-default">
  <div class="panel-heading panel-title">
    <h1>Brillient Content</h1>
  </div>
  </div>
    <% @blog_posts.each do |blog_post| %>
    <div class="col-md-6">
      <div class="panel">
      <tr>
        <div class="panel-heading">
          <p><strong><%= link_to blog_post.title, blog_post %></p>
        </div>
        <div class="panel-body">
          <p>by <strong><%= blog_post.user.username %></p>
          <p><%= blog_post.blog_entry[0..270] %>...[<%= link_to "READ MORE", blog_post %>]</p>
        </div>
      </tr>
      </div>
    </div>
    <% end %>
</div>

<br>

<%= link_to 'New Blog post', new_blog_post_path, class: "btn btn-custom"  %>

app/views/blog_posts/my_posts.html.erb
<p id="notice"><%= notice %></p>



<div class="row">
    <% @blog_posts.each do |blog_post| %>
    <div class="col-md-6">
      <div class="panel">
      <tr>
        <div class="panel-heading">
          <p><strong><%= link_to blog_post.title, blog_post %></p>
        </div>
        <div class="panel-body">
          <p>by <strong><%= blog_post.user.username %></p>
          <p><%= blog_post.blog_entry[0..270] %>...[<%= link_to "READ MORE", blog_post %>]</p>
        </div>
        <div class="panel-footer">
          <%= link_to 'Edit', edit_blog_post_path(blog_post),  class: "btn btn-warning"  %>
          <%= link_to 'Destroy', blog_post, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger"  %>
        </div>
      </tr>
      </div>
    </div>
    <% end %>
</div>

<br>

<%= link_to 'New Blog post', new_blog_post_path, class: "btn btn-custom" %>

app/views/blog_posts/new.html.erb
<h1>New Blog Post</h1>

<%= render 'form' %>

<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/show.html.erb
<p id="notice"><%= notice %></p>

<div class="panel panel-outline">
	<div class="panel-heading panel-custom">
		  <strong><%= @blog_post.user.username %></strong><br />
		  <%= @blog_post.created_at.strftime('%Y/%m/%d') %>
	</div>
	<div class="panel-body panel-trans">
		<h1><%= @blog_post.title %></h1><br />
		<p>
		  <%= @blog_post.blog_entry %>
		</p>
	</div>
</div>


    <div class="panel panel-outline">
      <div class="panel-body panel-trans">
		<%= render 'comments/form' %>
      </div>
    </div>


<div class="panel panel-outline">

		<div class="panel-heading panel-custom">
			<p>Comments</p>
		</div>
	<% @blog_post.comments.each do | comment | %>
		<div class="panel-body panel-trans">
			<p><%= comment.created_at.in_time_zone("Eastern Time (US & Canada)").strftime('%Y/%m/%d @ %l:%M:%S %p') %></p>
			<p>&nbsp;   <strong><%= comment.user.username %></strong> said: </p>
			<p>&nbsp;   <%= comment.comment_entry %></p>
		</div>
	<%end%>

</div>

<div>
	<%= link_to 'Back', blog_posts_path, class: "btn btn-custom"  %>
</div>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group cant-see-me">  
    <%= f.number_field :user_id, value: current_user.id %>
  </div>
  <div class="form-group">
    <%= f.label "Your thoughts" %><br>
    <%= f.text_area :comment_entry, class: "form-control", rows: "8" %>
  </div>
<!--   <div class="form-group">
    <%= f.label :comment_entry %><br>
    <%= f.text_area :comment_entry, class: "form-control", rows: "100%" %>
  </div> -->
  <div class="field cant-see-me">
    <%= f.label :blog_post_id %><br>
    <%= f.number_field :blog_post_id, value: @blog_post.id %>
  </div>
  <div class="actions">
    <%= f.submit "Share", class: "btn btn-custom" %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Author</th>
      <th>Comment entry</th>
      <th>Blog post</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.author %></td>
        <td><%= comment.comment_entry %></td>
        <td><%= comment.blog_post_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Author:</strong>
  <%= @comment.author %>
</p>

<p>
  <strong>Comment entry:</strong>
  <%= @comment.comment_entry %>
</p>

<p>
  <strong>Blog post:</strong>
  <%= @comment.blog_post_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %>


<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>CaptainsBlog</title>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

<%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" %>
<%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"%>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

<% if user_signed_in? %>
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Home", root_path, class: "navbar-brand" %>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Latest", blog_post_path(id: (BlogPost.all.length)) %></li>
          <li><%= link_to "Random", random_path %></li>
          <li><%= link_to "My Posts", my_posts_path %></li>
          <li><%= link_to "Users", users_path %></li>
        </ul>
        
            <ul class="nav navbar-nav navbar-right">
              <!-- <li>
                <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                  <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
                </form>
              </li> -->
              <li><form class="navbar-form"><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-default" %></form></li>
              <li><form class="navbar-form"><%= link_to "Profile", my_profile_path, class: "btn btn-default" %></form></li>
            </ul>
      </div>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
<% end %> 

<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/welcome/about.html.erb
<div class="row">
  <div class="panel panel-default panel-custom">
	  <div class=" panel-default">
	    <h1>About this blog...</h1>
	  </div>
  </div>
  <div class="panel panel-default panel-custom">
  	<div class="panel-body">
          <p>Creation was manditory.</p>
          <p>Here's some filler text:</p>
<!-- Comment -->
			<h1>The Series Has Landed</h1>
			<p>I just told you! You've killed me! I saw you with those two "ladies of the evening" at Elzars. Explain that. Professor, make a woman out of me.</p>
			<h2>The Cryonic Woman</h2>
			<p>Stop! Don't shoot fire stick in space canoe! Cause explosive decompression! You guys go on without me! I'm going to go&hellip; look for more stuff to steal! Interesting. No, wait, the other thing: tedious. Oh, how awful. Did he at least die painlessly? &hellip;To shreds, you say. Well, how is his wife holding up? &hellip;To shreds, you say.</p>
			<ul>
			<li>Alright, let's mafia things up a bit. Joey, burn down the ship. Clamps, burn down the crew.</li>
			<li>Of all the friends I've had&hellip; you're the first.</li>
			<li>And so we say goodbye to our beloved pet, Nibbler, who's gone to a place where I, too, hope one day to go. The toilet.</li>
			</ul>
			<h3>A Head in the Polls</h3>
			<p>I've been there. My folks were always on me to groom myself and wear underpants. What am I, the pope? Kif, I have mated with a woman. Inform the men. Who are those horrible orange men? When I was first asked to make a film about my nephew, Hubert Farnsworth, I thought "Why should I?" Then later, Leela made the film. But if I did make it, you can bet there would have been more topless women on motorcycles. Roll film! Who are those horrible orange men? Shut up and get to the point!</p>
			<h4>That Darn Katz!</h4>
			<p>Bender, this is Fry's decision&hellip; and he made it wrong. So it's time for us to interfere in his life. Doomsday device? Ah, now the ball's in Farnsworth's court! Of all the friends I've had&hellip; you're the first. I daresay that Fry has discovered the smelliest object in the known universe!</p>
			<ol>
			<li>No argument here.</li>
			<li>And so we say goodbye to our beloved pet, Nibbler, who's gone to a place where I, too, hope one day to go. The toilet.</li>
			</ol>
			<h5>Less Than Hero</h5>
			<p>Large bet on myself in round one. I usually try to keep my sadness pent up inside where it can fester quietly as a mental illness. Of all the friends I've had&hellip; you're the first. It's just like the story of the grasshopper and the octopus. All year long, the grasshopper kept burying acorns for winter, while the octopus mooched off his girlfriend and watched TV. But then the winter came, and the grasshopper died, and the octopus ate all his acorns. Also he got a race car. Is any of this getting through to you? Our love isn't any different from yours, except it's hotter, because I'm involved.</p>
			<h6>The Cryonic Woman</h6>
			<p>Oh, I always feared he might run off like this. Why, why, why didn't I break his legs? And when we woke up, we had these bodies. I suppose I could part with 'one' and still be feared&hellip;</p>
			<p>Hello Morbo, how's the family? Whoa a real live robot; or is that some kind of cheesy New Year's costume? Dr. Zoidberg, that doesn't make sense. But, okay! I suppose I could part with 'one' and still be feared&hellip; Guess again. Son, as your lawyer, I declare y'all are in a 12-piece bucket o' trouble. But I done struck you a deal: Five hours of community service cleanin' up that ol' mess you caused.</p>
			<p>Can we have Bender Burgers again? Alright, let's mafia things up a bit. Joey, burn down the ship. Clamps, burn down the crew. Ah, yes! John Quincy Adding Machine.  He struck a chord with the voters when he pledged not to go on a killing spree. Then throw her in the laundry room, which will hereafter be referred to as "the brig". Meh.</p>
			<p>Is the Space Pope reptilian!? File not found. Who am I making this out to? Man, I'm sore all over. I feel like I just went ten rounds with mighty Thor.</p>
			<p>Our love isn't any different from yours, except it's hotter, because I'm involved. I barely knew Philip, but as a clergyman I have no problem telling his most intimate friends all about him. Well I'da done better, but it's plum hard pleading a case while awaiting trial for that there incompetence. Yes, I saw. You were doing well, until everyone died.</p>
			<p>Well, then good news! It's a suppository. Calculon is gonna kill us and it's all everybody else's fault! Say what? Hey, whatcha watching? Come, Comrade Bender! We must take to the streets! And remember, don't do anything that affects anything, unless it turns out you were supposed to, in which case, for the love of God, don't not do it!</p>
			<p>No argument here. Who's brave enough to fly into something we all keep calling a death sphere? Pansy.</p>
			<p>No! The cat shelter's on to me. Come, Comrade Bender! We must take to the streets! Um, is this the boring, peaceful kind of taking to the streets? Yes, I saw. You were doing well, until everyone died. I love this planet! I've got wealth, fame, and access to the depths of sleaze that those things bring.</p>
			<p>Leela, Bender, we're going grave robbing. Robot 1-X, save my friends!  And Zoidberg! No argument here. It's okay, Bender. I like cooking too. Ok, we'll go deliver this crate like professionals, and then we'll go ride the bumper cars.</p>
			<p>Bender?! You stole the atom. Oh sure! Blame the wizards! With a warning label this big, you know they gotta be fun! I can explain. It's very valuable. Who said that? SURE you can die! You want to die?!</p>
			<p>OK, this has gotta stop. I'm going to remind Fry of his humanity the way only a woman can. Morbo will now introduce tonight's candidates&hellip; PUNY HUMAN NUMBER ONE, PUNY HUMAN NUMBER TWO, and Morbo's good friend, Richard Nixon. OK, if everyone's finished being stupid. Then we'll go with that data file! I can explain. It's very valuable. I didn't ask for a completely reasonable excuse! I asked you to get busy!</p>
			<p>Dr. Zoidberg, that doesn't make sense. But, okay! Okay, I like a challenge. Um, is this the boring, peaceful kind of taking to the streets? What are their names? You know the worst thing about being a slave? They make you work, but they don't pay you or let you go.</p>


    </div>
  </div>
 </div>

app/views/welcome/my_profile.html.erb
<div class="row">
    <div class="col-md-6">
      <div>
        <h2><%= @user.username %></h2>
      </div>
      <div class="panel">
        <div class="panel-body">
            <p>email: <%= @user.email %></p>
            <p>Location: <%= @user.location %></p>
            <p>DOB: <%= @user.birthday.strftime("%m/%d/%Y") %></p>
        </div>
      </div>
    </div>
</div>

<div><%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-custom" %></div>

app/views/welcome/random.html.erb
<h1>Welcome#random</h1>
<p>Find me in app/views/welcome/random.html.erb</p>

app/views/welcome/users.html.erb
<% @users.each do | user | %>
<div class="row">
    <div class="col-md-6">
      <div>
        <h2><%= user.username %></h2>
      </div>
      <div class="panel">
        <div class="panel-body">
            <p>email: <%= user.email %></p>
            <p>Location: <%= user.location %></p>
            <% if user.birthday != nil %>
            <p>DOB: <%= user.birthday.strftime("%m/%d/%Y") %></p>
            <%end%>
        </div>
      </div>
    </div>
</div>
<% end %>